const vocabData = {
    "1": [
{ "ja": "連絡", "en": "れんらく" },
{ "ja": "洗濯", "en": "せんたく" },
{ "ja": "結婚", "en": "けっこん" },
{ "ja": "結ぶ", "en": "むすぶ" },
{ "ja": "離婚", "en": "りこん" },
{ "ja": "運転", "en": "うんてん" },
{ "ja": "運ぶ", "en": "はこぶ" },
{ "ja": "案内", "en": "あんない" },
{ "ja": "提案", "en": "ていあん" },
{ "ja": "卒業", "en": "そつぎょう" },
{ "ja": "新卒者", "en": "しんそつしゃ" },
{ "ja": "利用", "en": "りよう" },
{ "ja": "用事", "en": "ようじ" },
{ "ja": "用意", "en": "ようい" },
{ "ja": "用いる", "en": "もちいる" },
{ "ja": "去年", "en": "きょねん" },
{ "ja": "過去", "en": "かこ" },
{ "ja": "趣味", "en": "しゅみ" },
{ "ja": "味", "en": "あじ" },
{ "ja": "味わう", "en": "あじわう" }
    ],
    "2": [
{ "ja": "授業", "en": "じゅぎょう" },
{ "ja": "橋", "en": "はし" },
{ "ja": "歩道橋", "en": "ほどうきょう" },
{ "ja": "花火", "en": "はなび" },
{ "ja": "薬局", "en": "やっきょく" },
{ "ja": "色", "en": "いろ" },
{ "ja": "特色", "en": "とくしょく" },
{ "ja": "服", "en": "ふく" },
{ "ja": "服装", "en": "ふくそう" },
{ "ja": "客", "en": "きゃく" },
{ "ja": "乗客", "en": "じょうきゃく" },
{ "ja": "客観的な", "en": "きゃっかんてきな" },
{ "ja": "犬", "en": "いぬ" },
{ "ja": "文", "en": "ぶん" },
{ "ja": "作文", "en": "さくぶん" },
{ "ja": "文化", "en": "ぶんか" },
{ "ja": "本物", "en": "ほんもの" },
{ "ja": "偽物", "en": "にせもの" },
{ "ja": "動物", "en": "どうぶつ" },
{ "ja": "植物", "en": "しょくぶつ" },
    ],
    "3": [
{ "ja": "生物学", "en": "せいぶつがく" },
{ "ja": "物理学", "en": "ぶつりがく" },
{ "ja": "物価", "en": "ぶっか" },
{ "ja": "食物", "en": "しょくもつ" },
{ "ja": "家族", "en": "かぞく" },
{ "ja": "公園", "en": "こうえん" },
{ "ja": "公の", "en": "おおやけの" },
{ "ja": "遊園地", "en": "ゆうえんち" },
{ "ja": "園芸", "en": "えんげい" },
{ "ja": "医者", "en": "いしゃ" },
{ "ja": "医学", "en": "いがく" },
{ "ja": "女医", "en": "じょい" },
{ "ja": "宿題", "en": "しゅくだい" },
{ "ja": "宿泊", "en": "しゅくはく" },
{ "ja": "問題", "en": "もんだい" },
{ "ja": "寺", "en": "てら" },
{ "ja": "図書館", "en": "としょかん" },
{ "ja": "地図", "en": "ちず" },
{ "ja": "図る", "en": "はかる" },
{ "ja": "教室", "en": "きょうしつ" },
    ],
    "4": [
{ "ja": "出席", "en": "しゅっせき" },
{ "ja": "欠席", "en": "けっせき" },
{ "ja": "座席", "en": "ざせき" },
{ "ja": "着席", "en": "ちゃくせき" },
{ "ja": "今度", "en": "こんど" },
{ "ja": "毎度", "en": "まいど" },
{ "ja": "度々", "en": "たびたび" },
{ "ja": "この度", "en": "このたび" },
{ "ja": "飛行機", "en": "ひこうき" },
{ "ja": "機内", "en": "きない" },
{ "ja": "場所", "en": "ばしょ" },
{ "ja": "場合", "en": "ばあい" },
{ "ja": "市場", "en": "しじょう" },
{ "ja": "県", "en": "けん" },
{ "ja": "県庁", "en": "けんちょう" },
{ "ja": "東京都", "en": "とうきょうと" },
{ "ja": "暖かい", "en": "あたたかい" },
{ "ja": "暖房", "en": "だんぼう" },
{ "ja": "涼しい", "en": "すずしい" },
{ "ja": "悲しい", "en": "かなしい" },
    ],
    "5": [
{ "ja": "苦しい", "en": "くるしい" },
{ "ja": "苦い", "en": "にがい" },
{ "ja": "楽しい", "en": "たのしい" },
{ "ja": "楽な", "en": "らくな" },
{ "ja": "気楽に", "en": "きらくに" },
{ "ja": "楽園", "en": "らくえん" },
{ "ja": "辛い", "en": "からい" },
{ "ja": "香辛料", "en": "こうしんりょう" },
{ "ja": "甘い", "en": "あまい" },
{ "ja": "痛い", "en": "いたい" },
{ "ja": "頭痛", "en": "ずつう" },
{ "ja": "有名な", "en": "ゆうめいな" },
{ "ja": "有る", "en": "ある" },
{ "ja": "退屈な", "en": "たいくつな" },
{ "ja": "早退", "en": "そうたい" },
{ "ja": "退院", "en": "たいいん" },
{ "ja": "引退", "en": "いんたい" },
{ "ja": "同じ", "en": "おなじ" },
{ "ja": "同意", "en": "どうい" },
{ "ja": "平和", "en": "へいわ" },
    ],
    "6": [
{ "ja": "平日", "en": "へいじつ" },
{ "ja": "平らな", "en": "たいらな" },
{ "ja": "和らげる", "en": "やわらげる" },
{ "ja": "平等", "en": "びょうどう" },
{ "ja": "同等の", "en": "どうとうの" },
{ "ja": "等しい", "en": "ひとしい" },
{ "ja": "第一に", "en": "だいいちに" },
{ "ja": "第三者", "en": "だいさんしゃ" },
{ "ja": "筆", "en": "ふで" },
{ "ja": "計算", "en": "けいさん" },
{ "ja": "切符", "en": "きっぷ" },
{ "ja": "簡単な", "en": "かんたんな" },
{ "ja": "単語", "en": "たんご" },
{ "ja": "単位", "en": "たんい" },
{ "ja": "戦争", "en": "せんそう" },
{ "ja": "戦う", "en": "たたかう" },
{ "ja": "反対", "en": "はんたい" },
{ "ja": "反面", "en": "はんめん" },
{ "ja": "村", "en": "むら" },
{ "ja": "付く", "en": "つく" },
{ "ja": "交付", "en": "こうふ" },
{ "ja": "団体", "en": "だんたい" },
    ],
    "7": [
{ "ja": "寸法", "en": "すんぽう" },
{ "ja": "支店", "en": "してん" },
{ "ja": "支える", "en": "ささえる" },
{ "ja": "技術", "en": "ぎじゅつ" },
{ "ja": "手術", "en": "しゅじゅつ" },
{ "ja": "街", "en": "まち" },
{ "ja": "封筒", "en": "ふうとう" },
{ "ja": "竹", "en": "たけ" },
{ "ja": "両替え", "en": "りょうがえ" },
{ "ja": "着替え", "en": "きがえ" },
{ "ja": "賛成", "en": "さんせい" },
{ "ja": "成功", "en": "せいこう" },
{ "ja": "工場", "en": "こうじょう" },
{ "ja": "工事", "en": "こうじ" },
{ "ja": "大工", "en": "だいく" },
{ "ja": "目的", "en": "もくてき" },
{ "ja": "約束", "en": "やくそく" },
{ "ja": "約―", "en": "やく" },
{ "ja": "束", "en": "たば" },
{ "ja": "速い", "en": "はやい" },
{ "ja": "速度", "en": "そくど" },
{ "ja": "早速", "en": "さっそく" },
{ "ja": "速やかに", "en": "すみやかに" },
    ],
    "8": [
{ "ja": "逆の", "en": "ぎゃくの" },
{ "ja": "整理", "en": "せいり" },
{ "ja": "整える", "en": "ととのえる" },
{ "ja": "事務", "en": "じむ" },
{ "ja": "務める", "en": "つとめる" },
{ "ja": "外務省", "en": "がいむしょう" },
{ "ja": "相談", "en": "そうだん" },
{ "ja": "相手", "en": "あいて" },
{ "ja": "理想", "en": "りそう" },
{ "ja": "首", "en": "くび" },
{ "ja": "出身", "en": "しゅっしん" },
{ "ja": "身分", "en": "みぶん" },
{ "ja": "社員", "en": "しゃいん" },
{ "ja": "損", "en": "そん" },
{ "ja": "区別", "en": "くべつ" },
{ "ja": "差別", "en": "さべつ" },
{ "ja": "特別な", "en": "とくべつな" },
{ "ja": "特急", "en": "とっきゅう" },
{ "ja": "特色", "en": "とくしょく" },
{ "ja": "特長", "en": "とくちょう" },
{ "ja": "特に", "en": "とくに" },
{ "ja": "点火", "en": "てんか" },
{ "ja": "点検", "en": "てんけん" },
{ "ja": "無理な", "en": "むりな" },
{ "ja": "無料の", "en": "むりょうの" },
{ "ja": "無口な", "en": "むくちな" },
    ],
    "9": [
{ "ja": "自然", "en": "しぜん" },
{ "ja": "全然", "en": "ぜんぜん" },
{ "ja": "当たる", "en": "あたる" },
{ "ja": "当たり前", "en": "あたりまえ" },
{ "ja": "当てはめる", "en": "あてはめる" },
{ "ja": "心当たり", "en": "こころあたり" },
{ "ja": "予定", "en": "よてい" },
{ "ja": "予約", "en": "よやく" },
{ "ja": "予想", "en": "よそう" },
{ "ja": "野生の", "en": "やせいの" },
{ "ja": "野菜", "en": "やさい" },
{ "ja": "原因", "en": "げんいん" },
{ "ja": "原料", "en": "げんりょう" },
{ "ja": "正しい", "en": "ただしい" },
{ "ja": "正解", "en": "せいかい" },
{ "ja": "正直な", "en": "しょうじきな" },
{ "ja": "正面", "en": "しょうめん" },
{ "ja": "正に", "en": "まさに" },
{ "ja": "糸", "en": "いと" },
{ "ja": "高級な", "en": "こうきゅうな" },
    ],
    "10": [
{ "ja": "同級生", "en": "どうきゅうせい" },
{ "ja": "初級", "en": "しょきゅう" },
{ "ja": "中級", "en": "ちゅうきゅう" },
{ "ja": "上級", "en": "じょうきゅう" },
{ "ja": "学級", "en": "がっきゅう" },
{ "ja": "能力", "en": "のうりょく" },
{ "ja": "可能な", "en": "かのうな" },
{ "ja": "世代", "en": "せだい" },
{ "ja": "時代", "en": "じだい" },
{ "ja": "現代", "en": "げんだい" },
{ "ja": "代理", "en": "だいり" },
{ "ja": "代わりに", "en": "かわりに" },
{ "ja": "文化", "en": "ぶんか" },
{ "ja": "化学", "en": "かがく" },
{ "ja": "強化", "en": "きょうか" },
{ "ja": "他人", "en": "たにん" },
{ "ja": "仏教", "en": "ぶっきょう" },
{ "ja": "仏", "en": "ほとけ" },
{ "ja": "位置", "en": "いち" },
{ "ja": "子供", "en": "こども" },
{ "ja": "供える", "en": "そなえる" },
{ "ja": "共に", "en": "ともに" },
{ "ja": "以上", "en": "いじょう" },
    ],
    "11": [
      { "ja": "います", "en": "have (children)" }, { "ja": "います", "en": "stay, be (in Japan)" }, { "ja": "かかります", "en": "take (time or money)" }, { "ja": "やすみます", "en": "take a day off (work)" }, { "ja": "ひとつ", "en": "one (item)" }, { "ja": "ふたつ", "en": "two (items)" }, { "ja": "みっつ", "en": "three (items)" }, { "ja": "よっつ", "en": "four (items)" }, { "ja": "いつつ", "en": "five (items)" }, { "ja": "むっつ", "en": "six (items)" }, { "ja": "ななつ", "en": "seven (items)" }, { "ja": "やっつ", "en": "eight (items)" }, { "ja": "ここのつ", "en": "nine (items)" }, { "ja": "とお", "en": "ten (items)" }, { "ja": "いくつ", "en": "how many" }, { "ja": "ひとり", "en": "one person" }, { "ja": "ふたり", "en": "two people" }, { "ja": "～にん", "en": "~ people" }, { "ja": "～だい", "en": "(counter for machines, cars, etc.)" }, { "ja": "～まい", "en": "(counter for flat things, e.g., paper, shirts)" }, { "ja": "～かい", "en": "~ times" }, { "ja": "りんご", "en": "apple" }, { "ja": "みかん", "en": "mandarin orange" }, { "ja": "サンドイッチ", "en": "sandwich" }, { "ja": "カレーライス", "en": "curry and rice" }, { "ja": "アイスクリーム", "en": "ice cream" }, { "ja": "きって", "en": "postage stamp" }, { "ja": "はがき", "en": "postcard" }, { "ja": "ふうとう", "en": "envelope" }, { "ja": "りょうしん", "en": "parents" }, { "ja": "きょうだい", "en": "brothers and sisters" }, { "ja": "あに", "en": "(my) older brother" }, { "ja": "おにいさん", "en": "(someone else's) older brother" }, { "ja": "あね", "en": "(my) older sister" }, { "ja": "おねえさん", "en": "(someone else's) older sister" }, { "ja": "おとうと", "en": "(my) younger brother" }, { "ja": "おとうとさん", "en": "(someone else's) younger brother" }, { "ja": "いもうと", "en": "(my) younger sister" }, { "ja": "いもうとさん", "en": "(someone else's) younger sister" }, { "ja": "がいこく", "en": "foreign country" }, { "ja": "りゅうがくせい", "en": "foreign student" }, { "ja": "クラス", "en": "class" }, { "ja": "じかん", "en": "~ hour(s)" }, { "ja": "しゅうかん", "en": "~ week(s)" }, { "ja": "かげつ", "en": "~ month(s)" }, { "ja": "ねん", "en": "~ year(s)" }, { "ja": "ぐらい", "en": "about ~" }, { "ja": "どのくらい", "en": "how long" }, { "ja": "ぜんぶで", "en": "in total" }, { "ja": "みんな", "en": "all, everything, everyone" }, { "ja": "だけ", "en": "only ~" }
    ],
    "12": [
      { "ja": "かんたん", "en": "easy, simple" }, { "ja": "ちかい", "en": "near" }, { "ja": "とおい", "en": "far" }, { "ja": "はやい", "en": "fast, early" }, { "ja": "おそい", "en": "late, slow" }, { "ja": "おおい", "en": "many, much (people)" }, { "ja": "すくない", "en": "few, a little (people)" }, { "ja": "あたたかい", "en": "warm" }, { "ja": "すずしい", "en": "cool" }, { "ja": "あまい", "en": "sweet" }, { "ja": "からい", "en": "hot (spicy), salty" }, { "ja": "おもい", "en": "heavy" }, { "ja": "かるい", "en": "light (in weight)" }, { "ja": "いい", "en": "prefer (coffee)" }, { "ja": "きせつ", "en": "season" }, { "ja": "はる", "en": "spring" }, { "ja": "なつ", "en": "summer" }, { "ja": "あき", "en": "autumn, fall" }, { "ja": "ふゆ", "en": "winter" }, { "ja": "てんき", "en": "weather" }, { "ja": "あめ", "en": "rain, rainy" }, { "ja": "ゆき", "en": "snow, snowy" }, { "ja": "くもり", "en": "cloudy" }, { "ja": "ホテル", "en": "hotel" }, { "ja": "くうこう", "en": "airport" }, { "ja": "うみ", "en": "sea, ocean" }, { "ja": "せかい", "en": "world" }, { "ja": "パーティー", "en": "party" }, { "ja": "おまつり", "en": "festival" }, { "ja": "すきやき", "en": "sukiyaki" }, { "ja": "さしみ", "en": "sashimi (sliced raw fish)" }, { "ja": "おすし", "en": "sushi (vinegared rice with fish)" }, { "ja": "てんぷら", "en": "tempura" }, { "ja": "ぶたにく", "en": "pork" }, { "ja": "とりにく", "en": "chicken" }, { "ja": "ぎゅうにく", "en": "beef" }, { "ja": "レモン", "en": "lemon" }, { "ja": "いけばな", "en": "flower arrangement" }, { "ja": "もみじ", "en": "maple, red leaves of autumn" }, { "ja": "どちら", "en": "which one (of two)" }, { "ja": "どちらも", "en": "both" }, { "ja": "いちばん", "en": "the most" }, { "ja": "ずっと", "en": "by far" }, { "ja": "はじめて", "en": "for the first time" }
    ],
    "13": [
      { "ja": "あそびます", "en": "play, enjoy oneself" }, { "ja": "およぎます", "en": "swim" }, { "ja": "むかえます", "en": "go to meet, welcome" }, { "ja": "つかれます", "en": "get tired" }, { "ja": "だします", "en": "send (a letter)" }, { "ja": "はいります", "en": "enter (a coffee shop)" }, { "ja": "でます", "en": "go out (of a coffee shop)" }, { "ja": "けっこんします", "en": "marry, get married" }, { "ja": "かいものします", "en": "do shopping" }, { "ja": "しょくじします", "en": "have a meal, dine" }, { "ja": "さんぽします", "en": "take a walk (in a park)" }, { "ja": "たいへん", "en": "hard, tough, severe, awful" }, { "ja": "ほしい", "en": "want (something)" }, { "ja": "さびしい", "en": "lonely" }, { "ja": "ひろい", "en": "wide, spacious" }, { "ja": "せまい", "en": "narrow, small (room, etc.)" }, { "ja": "しやくしょ", "en": "municipal office, city hall" }, { "ja": "プール", "en": "swimming pool" }, { "ja": "かわ", "en": "river" }, { "ja": "けいざい", "en": "economy" }, { "ja": "びじゅつ", "en": "fine arts" }, { "ja": "つり", "en": "fishing" }, { "ja": "スキー", "en": "skiing" }, { "ja": "かいぎ", "en": "meeting, conference" }, { "ja": "とうろく", "en": "registration" }, { "ja": "しゅうまつ", "en": "weekend" }, { "ja": "ごろ", "en": "about (time)" }, { "ja": "なにか", "en": "something" }, { "ja": "どこか", "en": "somewhere, some place" }, { "ja": "おなかがすきました", "en": "I'm hungry" }, { "ja": "おなかがいっぱいです", "en": "I'm full" }, { "ja": "のどがかわきました", "en": "I'm thirsty" }
    ],
    "14": [
      { "ja": "つけます", "en": "turn on" }, { "ja": "けします", "en": "turn off" }, { "ja": "あけます", "en": "open" }, { "ja": "しめます", "en": "close, shut" }, { "ja": "いそぎます", "en": "hurry" }, { "ja": "まちます", "en": "wait" }, { "ja": "とめます", "en": "stop, park" }, { "ja": "まがります", "en": "turn (right)" }, { "ja": "もちます", "en": "hold" }, { "ja": "とります", "en": "take, pass" }, { "ja": "てつだいます", "en": "help (with a task)" }, { "ja": "よびます", "en": "call" }, { "ja": "はなします", "en": "speak, talk" }, { "ja": "みせます", "en": "show" }, { "ja": "おしえます", "en": "tell (an address)" }, { "ja": "はじめます", "en": "start, begin" }, { "ja": "ふります", "en": "rain" }, { "ja": "コピーします", "en": "copy" }, { "ja": "エアコン", "en": "air conditioner" }, { "ja": "パスポート", "en": "passport" }, { "ja": "なまえ", "en": "name" }, { "ja": "じゅうしょ", "en": "address" }, { "ja": "ちず", "en": "map" }, { "ja": "しお", "en": "salt" }, { "ja": "さとう", "en": "sugar" }, { "ja": "よみかた", "en": "how to read, way of reading" }, { "ja": "かた", "en": "how to ~, way of ~ing" }, { "ja": "ゆっくり", "en": "slowly, leisurely" }, { "ja": "すぐ", "en": "immediately" }, { "ja": "また", "en": "again" }, { "ja": "あとで", "en": "later" }, { "ja": "もうすこし", "en": "a little more" }, { "ja": "もう", "en": "~ more, another ~" }
    ],
    "15": [
      { "ja": "たちます", "en": "stand up" }, { "ja": "すわります", "en": "sit down" }, { "ja": "つかいます", "en": "use" }, { "ja": "おきます", "en": "put" }, { "ja": "つくります", "en": "make, produce" }, { "ja": "うります", "en": "sell" }, { "ja": "しります", "en": "get to know" }, { "ja": "すみます", "en": "be going to live" }, { "ja": "けんきゅうします", "en": "do research" }, { "ja": "しっています", "en": "know" }, { "ja": "すんでいます", "en": "live (in Osaka)" }, { "ja": "しりょう", "en": "materials, data" }, { "ja": "カタログ", "en": "catalog" }, { "ja": "じこくひょう", "en": "timetable" }, { "ja": "ふく", "en": "clothes" }, { "ja": "せいひん", "en": "products" }, { "ja": "ソフト", "en": "software" }, { "ja": "でんしじしょ", "en": "electronic dictionary" }, { "ja": "けいざい", "en": "economy" }, { "ja": "しやくしょ", "en": "city hall" }, { "ja": "こうこう", "en": "senior high school" }, { "ja": "はいしゃ", "en": "dentist, dentist's" }, { "ja": "どくしん", "en": "single, unmarried" }
    ],
    "16": [
      { "ja": "のります", "en": "get on, board" }, { "ja": "おります", "en": "get off, alight" }, { "ja": "のりかえます", "en": "change (trains, etc.)" }, { "ja": "あびます", "en": "take (a shower)" }, { "ja": "いれます", "en": "put in, insert" }, { "ja": "だします", "en": "take out, hand in, pay" }, { "ja": "はいります", "en": "enter (university)" }, { "ja": "でます", "en": "graduate from (university)" }, { "ja": "やめます", "en": "quit or retire from (a company), stop, give up" }, { "ja": "おします", "en": "push, press" }, { "ja": "わかい", "en": "young" }, { "ja": "ながい", "en": "long" }, { "ja": "みじかい", "en": "short" }, { "ja": "あかるい", "en": "bright, light" }, { "ja": "くらい", "en": "dark" }, { "ja": "せがたかい", "en": "tall (referring to person)" }, { "ja": "あたまがいい", "en": "clever, smart" }, { "ja": "からだ", "en": "body" }, { "ja": "あたま", "en": "head" }, { "ja": "かみ", "en": "hair" }, { "ja": "かお", "en": "face" }, { "ja": "め", "en": "eye" }, { "ja": "みみ", "en": "ear" }, { "ja": "くち", "en": "mouth" }, { "ja": "は", "en": "tooth" }, { "ja": "おなか", "en": "stomach" }, { "ja": "あし", "en": "leg, foot" }, { "ja": "サービス", "en": "service" }, { "ja": "ジョギング", "en": "jogging" }, { "ja": "シャワー", "en": "shower" }, { "ja": "みどり", "en": "green, greenery" }, { "ja": "おてら", "en": "Buddhist temple" }, { "ja": "じんじゃ", "en": "Shinto shrine" }, { "ja": "りゅうがくせい", "en": "foreign student" }, { "ja": "ばん", "en": "number ~" }, { "ja": "どうやって", "en": "in what way, how" }, { "ja": "どの", "en": "which ~ (used for three or more)" }, { "ja": "どれ", "en": "which one (of three or more)" }
    ],
    "17": [
      { "ja": "おぼえます", "en": "memorize" }, { "ja": "わすれます", "en": "forget" }, { "ja": "なくします", "en": "lose" }, { "ja": "だします", "en": "hand in (a report)" }, { "ja": "はらいます", "en": "pay" }, { "ja": "かえします", "en": "give back, return" }, { "ja": "でかけます", "en": "go out" }, { "ja": "ぬぎます", "en": "take off (clothes, shoes, etc.)" }, { "ja": "もっていきます", "en": "take (something)" }, { "ja": "もってきます", "en": "bring (something)" }, { "ja": "しんぱいします", "en": "worry" }, { "ja": "ざんぎょうします", "en": "work overtime" }, { "ja": "しゅっちょうします", "en": "go on a business trip" }, { "ja": "のみます", "en": "take (medicine)" }, { "ja": "はいります", "en": "take (a bath)" }, { "ja": "たいせつ", "en": "important, precious" }, { "ja": "だいじょうぶ", "en": "all right" }, { "ja": "あぶない", "en": "dangerous" }, { "ja": "もんだい", "en": "question, problem, trouble" }, { "ja": "こたえ", "en": "answer" }, { "ja": "きんえん", "en": "no smoking" }, { "ja": "けんこうほけんしょう", "en": "health insurance card" }, { "ja": "かぜ", "en": "a cold" }, { "ja": "ねつ", "en": "fever" }, { "ja": "びょうき", "en": "illness, disease" }, { "ja": "くすり", "en": "medicine" }, { "ja": "おふろ", "en": "bath" }, { "ja": "うわぎ", "en": "jacket, outerwear" }, { "ja": "したぎ", "en": "underwear" }, { "ja": "せんせい", "en": "doctor (used when addressing a medical doctor)" }, { "ja": "に", "en": "a few days" }, { "ja": "までに", "en": "before, by (indicating time limit)" }, { "ja": "ですから", "en": "therefore, so" }
    ],
    "18": [
      { "ja": "できます", "en": "be able to, can" }, { "ja": "あらいます", "en": "wash" }, { "ja": "ひきます", "en": "play (string instrument or piano, etc.)" }, { "ja": "うたいます", "en": "sing" }, { "ja": "あつめます", "en": "collect, gather" }, { "ja": "すてます", "en": "throw away" }, { "ja": "かえます", "en": "exchange, change" }, { "ja": "うんてんします", "en": "drive" }, { "ja": "よやくします", "en": "reserve, book" }, { "ja": "けんがくします", "en": "visit some place for study" }, { "ja": "ピアノ", "en": "piano" }, { "ja": "メートル", "en": "meter" }, { "ja": "こくさい", "en": "international" }, { "ja": "げんきん", "en": "cash" }, { "ja": "しゅみ", "en": "hobby" }, { "ja": "にっき", "en": "diary" }, { "ja": "おいのり", "en": "prayer" }, { "ja": "かちょう", "en": "section chief" }, { "ja": "ぶちょう", "en": "department chief" }, { "ja": "しゃちょう", "en": "president of a company" }, { "ja": "どうぶつ", "en": "animal" }, { "ja": "うま", "en": "horse" }, { "ja": "へえ", "en": "really! (used when expressing surprise)" }, { "ja": "それはおもしろいですね", "en": "That must be interesting" }, { "ja": "なかなか", "en": "not easily (used with negatives)" }, { "ja": "ぼく", "en": "I (informal equivalent of watashi used by men)" }, { "ja": "ぜひ", "en": "by all means" }
    ],
    "19": [
      { "ja": "のぼります", "en": "climb, go up" }, { "ja": "とまります", "en": "stay (at a hotel)" }, { "ja": "そうじします", "en": "clean (a room)" }, { "ja": "せんたくします", "en": "wash (clothes)" }, { "ja": "れんしゅうします", "en": "practice" }, { "ja": "なります", "en": "become" }, { "ja": "ねむい", "en": "sleepy" }, { "ja": "つよい", "en": "strong" }, { "ja": "よわい", "en": "weak" }, { "ja": "ちょうしがいい", "en": "be in good condition" }, { "ja": "ちょうしがわるい", "en": "be in bad condition" }, { "ja": "ちょうし", "en": "condition" }, { "ja": "ゴルフ", "en": "golf" }, { "ja": "すもう", "en": "sumo wrestling" }, { "ja": "パチンコ", "en": "pachinko (Japanese pinball)" }, { "ja": "おちゃ", "en": "tea ceremony" }, { "ja": "ひ", "en": "day, date" }, { "ja": "いちど", "en": "once" }, { "ja": "いちども", "en": "not once, never (used with negatives)" }, { "ja": "だんだん", "en": "gradually" }, { "ja": "もうすぐ", "en": "soon" }, { "ja": "おかげさまで", "en": "Thank you (used when expressing gratitude for help received)" }, { "ja": "かんぱい", "en": "Bottoms up / Cheers!" }, { "ja": "ダイエット", "en": "diet" }, { "ja": "むり", "en": "excessive, impossible" }, { "ja": "からだにいい", "en": "good for one's health" }
    ],
    "20": [
      { "ja": "いります", "en": "need, require (a visa)" }, { "ja": "しらべます", "en": "check, investigate" }, { "ja": "なおします", "en": "repair, correct" }, { "ja": "しゅうりします", "en": "repair" }, { "ja": "でんわします", "en": "phone" }, { "ja": "ぼく", "en": "I (informal equivalent of watashi used by men)" }, { "ja": "きみ", "en": "you (informal equivalent of anata used by men)" }, { "ja": "くん", "en": "Mr. (informal equivalent of ~san used by men)" }, { "ja": "うん", "en": "yes (informal equivalent of hai)" }, { "ja": "ううん", "en": "no (informal equivalent of iie)" }, { "ja": "サラリーマン", "en": "salaryman, company employee" }, { "ja": "ことば", "en": "word, language" }, { "ja": "ぶっか", "en": "commodity prices" }, { "ja": "きもの", "en": "kimono (traditional Japanese attire)" }, { "ja": "ビザ", "en": "visa" }, { "ja": "はじめ", "en": "the beginning" }, { "ja": "おわり", "en": "the end" }, { "ja": "こっち", "en": "this way, this place (informal equivalent of kochira)" }, { "ja": "そっち", "en": "that way, that place (informal equivalent of sochira)" }, { "ja": "あっち", "en": "that way, that place over there (informal equivalent of achira)" }, { "ja": "どっち", "en": "which one (between two things), which way, where (informal equivalent of dochira)" }, { "ja": "このあいだ", "en": "the other day" }, { "ja": "みんなで", "en": "all together" }, { "ja": "けど", "en": "but (informal equivalent of ga)" }
    ],
    "21": [
      { "ja": "おもいます", "en": "think" }, { "ja": "いいします", "en": "say" }, { "ja": "たります", "en": "be enough, be sufficient" }, { "ja": "かちます", "en": "win" }, { "ja": "まけます", "en": "lose, be beaten" }, { "ja": "あります", "en": "be held, take place (a festival)" }, { "ja": "やくにたちます", "en": "be useful" }, { "ja": "むだ", "en": "wasteful" }, { "ja": "ふべん", "en": "inconvenient" }, { "ja": "おなじ", "en": "the same" }, { "ja": "すごい", "en": "awful, great (expresses astonishment or admiration)" }, { "ja": "しゅしょう", "en": "prime minister" }, { "ja": "だいとうりょう", "en": "president" }, { "ja": "せいじ", "en": "politics" }, { "ja": "ニュース", "en": "news" }, { "ja": "スピーチ", "en": "speech" }, { "ja": "しあい", "en": "game, match" }, { "ja": "アルバイト", "en": "side job" }, { "ja": "いけん", "en": "opinion" }, { "ja": "おはなし", "en": "talk, speech, what one says, story" }, { "ja": "ユーモア", "en": "humor" }, { "ja": "むだ", "en": "waste" }, { "ja": "デザイン", "en": "design" }, { "ja": "こうつう", "en": "transportation, traffic" }, { "ja": "ラッシュ", "en": "rush hour" }, { "ja": "さいきん", "en": "recently, these days" }, { "ja": "たぶん", "en": "probably, perhaps, maybe" }, { "ja": "きっと", "en": "surely" }, { "ja": "ほんとうに", "en": "really" }, { "ja": "そんなに", "en": "not so (used with negatives)" }, { "ja": "について", "en": "about ~, concerning ~" }
    ],
    "22": [
      { "ja": "きます", "en": "put on (a shirt, etc.)" }, { "ja": "はきます", "en": "put on (shoes, trousers, etc.)" }, { "ja": "かぶります", "en": "put on (a hat, etc.)" }, { "ja": "かけます", "en": "put on (glasses)" }, { "ja": "うまれます", "en": "be born" }, { "ja": "コート", "en": "coat" }, { "ja": "スーツ", "en": "suit" }, { "ja": "セーター", "en": "sweater" }, { "ja": "ぼうし", "en": "hat, cap" }, { "ja": "めがね", "en": "glasses" }, { "ja": "よく", "en": "often" }, { "ja": "おめでとうございます", "en": "Congratulations" }, { "ja": "こちら", "en": "this (polite equivalent of kore)" }, { "ja": "やちん", "en": "house rent" }, { "ja": "うーん", "en": "Let me see" }, { "ja": "ダイニングキチン", "en": "kitchen with a dining area" }, { "ja": "わしつ", "en": "Japanese-style room" }, { "ja": "おしいれ", "en": "Japanese-style closet" }, { "ja": "ふとん", "en": "Japanese-style mattress and quilt" }, { "ja": "アパート", "en": "apartment" }
    ],
    "23": [
      { "ja": "ききます", "en": "ask (the teacher)" }, { "ja": "まわします", "en": "turn" }, { "ja": "ひきます", "en": "pull" }, { "ja": "かえます", "en": "change" }, { "ja": "さわります", "en": "touch (a door)" }, { "ja": "でます", "en": "come out (change)" }, { "ja": "あるきます", "en": "walk" }, { "ja": "わたります", "en": "cross (a bridge)" }, { "ja": "まがります", "en": "turn (right)" }, { "ja": "さびしい", "en": "lonely" }, { "ja": "おゆ", "en": "hot water" }, { "ja": "おと", "en": "sound" }, { "ja": "サイズ", "en": "size" }, { "ja": "こしょう", "en": "breakdown" }, { "ja": "みち", "en": "road, way" }, { "ja": "こうさてん", "en": "crossroads" }, { "ja": "しんごう", "en": "traffic light" }, { "ja": "かど", "en": "corner" }, { "ja": "はし", "en": "bridge" }, { "ja": "ちゅうしゃじょう", "en": "parking lot" }, { "ja": "め", "en": "the -th (indicating order)" }, { "ja": "おしょうがつ", "en": "New Year's Day" }
    ],
    "24": [
      { "ja": "くれます", "en": "give (me)" }, { "ja": "なおします", "en": "repair, correct" }, { "ja": "つれていきます", "en": "take (someone)" }, { "ja": "つれてきます", "en": "bring (someone)" }, { "ja": "おくります", "en": "escort (someone), go with" }, { "ja": "しょうかいします", "en": "introduce" }, { "ja": "あんないします", "en": "show around, show the way" }, { "ja": "せつめいします", "en": "explain" }, { "ja": "おじいさん", "en": "grandfather, old man" }, { "ja": "おばあさん", "en": "grandmother, old woman" }, { "ja": "じゅんび", "en": "preparation" }, { "ja": "いみ", "en": "meaning" }, { "ja": "おかし", "en": "sweets, snacks" }, { "ja": "ぜんぶ", "en": "all" }, { "ja": "じぶんで", "en": "by oneself" }, { "ja": "ほかに", "en": "besides" }, { "ja": "ワゴンしゃ", "en": "station wagon" }
    ],
    "25": [
      { "ja": "かんがえます", "en": "think, consider" }, { "ja": "つきます", "en": "arrive (at a station)" }, { "ja": "りゅうがくします", "en": "study abroad" }, { "ja": "とります", "en": "grow old" }, { "ja": "いなか", "en": "countryside, hometown" }, { "ja": "たいしかん", "en": "embassy" }, { "ja": "グループ", "en": "group" }, { "ja": "チャンス", "en": "chance" }, { "ja": "おく", "en": "hundred million" }, { "ja": "もし", "en": "if" }, { "ja": "いくら", "en": "however ~, even if ~" }, { "ja": "てんきん", "en": "transfer" }, { "ja": "こと", "en": "thing, matter" }, { "ja": "がんばります", "en": "do one's best" }, { "ja": "どうぞおげんきで", "en": "Please take care of yourself" }, { "ja": "おせわになりました", "en": "Thank you for everything you have done for me" }
    ]
};
